[project]
name = "vale-docs-linter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.4.246",
    "docutils>=0.21.2",
    "pandas>=2.2.3",
    "rich>=13.9.4",
]
